# Generated by Django 3.2.5 on 2023-08-18 09:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('matrimony', '0002_auto_20230818_0752'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='religion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='matrimony.religion'),
        ),
    ]
