# Generated by Django 3.2.5 on 2023-08-20 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matrimony', '0003_profile_religion'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hobby',
            options={'verbose_name_plural': 'Hobbies'},
        ),
    ]
