# Generated by Django 3.2.5 on 2023-08-31 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matrimony', '0005_alter_profile_birth_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='hobby',
            field=models.ManyToManyField(related_name='profiles', to='matrimony.Hobby'),
        ),
    ]
